version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ecom_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  usersvc:
    build:
      context: ./services/usersvc
      dockerfile: Dockerfile
    container_name: usersvc
    ports:
      - "8080:8080"
    environment:
      - PG_URL=postgres://postgres:postgres@db:5432/usersvc?sslmode=disable
    depends_on:
      - db

  productsvc:
    build:
      context: ./services/productsvc
      dockerfile: Dockerfile
    container_name: productsvc
    ports:
      - "8082:8082"
    environment:
      - PG_URL=postgres://postgres:postgres@db:5432/productsvc?sslmode=disable
    depends_on:
      - db

  ordersvc:
    build:
      context: ./services/ordersvc
      dockerfile: Dockerfile
    container_name: ordersvc
    ports:
      - "8083:8083"
    environment:
      - PG_URL=postgres://postgres:postgres@db:5432/ordersvc?sslmode=disable
    depends_on:
      - db
      - usersvc
      - productsvc

volumes:
  pgdata: {}