apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordersvc
  template:
    metadata:
      labels:
        app: ordersvc
    spec:
      containers:
      - name: ordersvc
        image: raghavendrakm/ordersvc:latest
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: ordersdb
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ordersvc
spec:
  type: NodePort
  selector:
    app: ordersvc
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30083