apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usersvc
  template:
    metadata:
      labels:
        app: usersvc
    spec:
      containers:
      - name: usersvc
        image: raghavendrakm/usersvc:latest
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: usersdb
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: usersvc
spec:
  type: NodePort
  selector:
    app: usersvc
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30081