apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productsvc
  template:
    metadata:
      labels:
        app: productsvc
    spec:
      containers:
      - name: productsvc
        image: raghavendrakm/productsvc:latest
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: productsdb
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: productsvc
spec:
  type: NodePort
  selector:
    app: productsvc
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30082